package game.content.phantasye.skill.slayer;

public enum  Locations {

    SLAYER_TOWER,
    FREMENNIK_DUNGEON,
    WILDERNESS_VOLACANO,
    MORYTANIA,
    ARDOUGNE,
    VARROCK,
    EDGEVILLE_DUNGEON,
    TAVERLY_DUNGEON,
    BRIMHAVEN_DUNGEON,
    LAVA_MAZE,
    KING_BLACK_DRAGON,
    DUNGEONZONE,
    VORKATH,
    WARRIORS_GUILD,
    DAGANNOTH_KINGS,
    LUMBRIDGE,
    GENERAL_GRAARDOR,
    REVENANT_CAVES,
    EAST_DRAGONS,
    CERBERUS,
    ICE_STRYKEWYRMS,
    AL_KHARID,
    WYVERN_CAVE,
    TZHAAR,
    TORMENTED_DEMON;


}
